// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WasteManagementSystem.Data;

#nullable disable

namespace WasteManagementSystem.Migrations
{
    [DbContext(typeof(WasteContext))]
    partial class WasteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("WasteManagementSystem.Models.HouseDetails", b =>
                {
                    b.Property<string>("Eircode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Eircode");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("WasteManagementSystem.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseDetailsId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HouseDetailsId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("WasteManagementSystem.Models.WasteLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateWasted")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("WasteLogs");
                });

            modelBuilder.Entity("WasteManagementSystem.Models.Item", b =>
                {
                    b.HasOne("WasteManagementSystem.Models.HouseDetails", "House")
                        .WithMany("Items")
                        .HasForeignKey("HouseDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("WasteManagementSystem.Models.WasteLog", b =>
                {
                    b.HasOne("WasteManagementSystem.Models.Item", "Item")
                        .WithOne("WasteLog")
                        .HasForeignKey("WasteManagementSystem.Models.WasteLog", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WasteManagementSystem.Models.HouseDetails", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("WasteManagementSystem.Models.Item", b =>
                {
                    b.Navigation("WasteLog");
                });
#pragma warning restore 612, 618
        }
    }
}
